block while initializing app state
On our scenario, main window will query daily lifes from app state. But since we are initializing app state by async, query command can be invoked before app state initialized and managed.

We can block the process while initializing app state and successfully managed.

See full error logs:
```
thread 'tokio-runtime-worker' panicked at 'state not managed for field `appState` on command `get_daily_lifes`. You muse call `.manage()` before using this command', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-rc.8/src/state.rs:49:7
```